# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
