# Generated by Django 2.2 on 2019-08-07 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20170914_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
