# Generated by Django 2.2.17 on 2021-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_position_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='job_locations',
            field=models.CharField(default='', max_length=500),
        ),
    ]
