# Generated by Django 2.2.17 on 2021-04-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_position_job_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_mofo',
            field=models.BooleanField(default=False),
        ),
    ]
