# Generated by Django 2.2.24 on 2021-07-28 03:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heroHeader', wagtail.core.fields.RichTextField(blank=True)),
                ('heroText', wagtail.core.fields.RichTextField(blank=True)),
                ('videoUrlCode', models.CharField(max_length=255)),
                ('dataOneA', models.CharField(max_length=255)),
                ('dataOneB', models.CharField(max_length=255)),
                ('dataOneC', models.CharField(max_length=255)),
                ('leadOneTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('leadOneContent', wagtail.core.fields.RichTextField(blank=True)),
                ('SurveyContentTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('SurveyContentContent', wagtail.core.fields.RichTextField(blank=True)),
                ('ContentBlockOneVideoId', models.CharField(max_length=255)),
                ('ContentBlockOneTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('ContentBlockOneContent', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='HomeIndexPage',
        ),
    ]
