# Generated by Django 2.2.24 on 2021-07-28 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210728_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='HomeIndexPage',
        ),
    ]
