# Generated by Django 2.2.24 on 2021-07-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210728_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeindexpage',
            name='applyButtonText',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='applyButtonUrl',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
