# Generated by Django 2.2.24 on 2021-08-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0005_auto_20210729_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeindexpage',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='imageOne',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
