# Generated by Django 2.2.24 on 2021-08-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0006_auto_20210803_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeindexpage',
            old_name='image',
            new_name='imageA',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='imageOne',
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='imageB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
            preserve_default=False,
        ),
    ]
