# Generated by Django 2.2.24 on 2021-08-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210803_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeindexpage',
            old_name='heroOneHeader',
            new_name='heroHeader',
        ),
        migrations.RenameField(
            model_name='homeindexpage',
            old_name='heroOneText',
            new_name='heroText',
        ),
    ]
