# Generated by Django 2.2.24 on 2021-09-01 21:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0009_auto_20210817_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heroHeader', models.CharField(max_length=255)),
                ('heroText', models.CharField(max_length=255)),
                ('applyButtonUrl', models.CharField(max_length=255)),
                ('applyButtonText', models.CharField(max_length=255)),
                ('videoUrlCode', models.CharField(max_length=255)),
                ('dataOneA', models.CharField(max_length=255)),
                ('dataOneB', models.CharField(max_length=255)),
                ('dataOneC', models.CharField(max_length=255)),
                ('leadOneTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('leadOneContent', wagtail.core.fields.RichTextField(blank=True)),
                ('SurveyContentTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('SurveyContentContent', wagtail.core.fields.RichTextField(blank=True)),
                ('ContentBlockOneVideoId', models.CharField(max_length=255)),
                ('ContentBlockOneTitle', wagtail.core.fields.RichTextField(blank=True)),
                ('ContentBlockOneContent', wagtail.core.fields.RichTextField(blank=True)),
                ('imageA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imageB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imageC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imageD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imageE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('imageF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
